version: v0.0.0
appVersion: v0.0.0
annotations:
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/prerelease: 'false'
  artifacthub.io/license: MIT
  artifacthub.io/changes: ''
  artifacthub.io/links: |
    - name: Chart Sources
      url: https://github.com/enix/helm-charts/tree/master/charts/x509-certificate-exporter
    - name: Application Sources
      url: https://github.com/enix/x509-certificate-exporter
    - name: Helm Repository
      url: https://charts.enix.io
    - name: Grafana Dashboard
      url: https://grafana.com/grafana/dashboards/13922

apiVersion: v2
name: x509-certificate-exporter
type: application
description: A Prometheus exporter for certificates focusing on expiration monitoring
keywords:
  - prometheus
  - exporter
  - certificate
  - expiration
home: https://github.com/enix/x509-certificate-exporter
icon: https://github.githubassets.com/images/icons/emoji/unicode/1f50f.png
sources:
  - https://github.com/enix/x509-certificate-exporter
  - https://github.com/enix/helm-charts/tree/master/charts/x509-certificate-exporter
maintainers:
  - name: Enix
    email: contact@enix.fr
    url: https://github.com/enixsas
  - name: Thibault Vincent
    email: root@paraneko.org
    url: https://github.com/npdgm
  - name: Arthur Chaloin
    email: arthur.chaloin@enix.fr
